# Fail2Ban filter S5 Mail management daemon

[INCLUDES]

before = common.conf

[Definition]

_daemon = s5mail

failregex = S5 Mail Management Daemon: Failed login attempt from ip <HOST> - timestamp .*
ignoreregex =
