#!/bin/bash
# Rspamd filtering, Valkey state, and IMAPSieve learning
# --------------------------------------------------------

source setup/functions.sh
source /etc/s5mail.conf

echo "Installing Rspamd and Valkey..."
apt_install rspamd valkey-server

# Valkey is intentionally a single loopback-only instance. Its RDB lives in
# STORAGE_ROOT so the normal S5 backup includes greylisting, rate-limit, and
# Bayes state. allkeys-lru keeps the 1 GB appliance within its memory budget.
install -d -m 0750 /etc/valkey/valkey.conf.d
install -d -m 0750 -o valkey -g valkey "$STORAGE_ROOT/mail/valkey"
cat > /etc/valkey/valkey.conf.d/90-s5mail.conf << EOF
bind 127.0.0.1 ::1
protected-mode yes
port 6379
maxmemory 64mb
maxmemory-policy allkeys-lru
dir "$STORAGE_ROOT/mail/valkey"
dbfilename s5mail.rdb
appendonly no
save 900 1
save 300 10
EOF
if ! grep -Fqx 'include /etc/valkey/valkey.conf.d/*.conf' /etc/valkey/valkey.conf; then
	printf '\ninclude /etc/valkey/valkey.conf.d/*.conf\n' >> /etc/valkey/valkey.conf
fi
chown root:root /etc/valkey/valkey.conf.d/90-s5mail.conf
chmod 0644 /etc/valkey/valkey.conf.d/90-s5mail.conf
install -d -m 0755 /etc/systemd/system/valkey-server.service.d
cat > /etc/systemd/system/valkey-server.service.d/90-s5mail-storage.conf << EOF
[Service]
# Valkey persists its state under STORAGE_ROOT so S5 backups capture it.
# Debian's hardened unit otherwise hides /home and rejects this write path.
ProtectHome=false
ReadWritePaths=-$STORAGE_ROOT/mail/valkey
EOF
systemctl daemon-reload

install -d -m 0750 -o _rspamd -g _rspamd /etc/rspamd/local.d /etc/rspamd/override.d
install -d -m 2750 -o root -g _rspamd /etc/rspamd/s5mail-dkim
touch /etc/rspamd/s5mail-dkim/SigningTable /etc/rspamd/s5mail-dkim/KeyTable
chown root:_rspamd /etc/rspamd/s5mail-dkim/SigningTable /etc/rspamd/s5mail-dkim/KeyTable
chmod 0640 /etc/rspamd/s5mail-dkim/SigningTable /etc/rspamd/s5mail-dkim/KeyTable

# Postfix milter proxy. The controller and proxy both bind to loopback only.
cat > /etc/rspamd/local.d/worker-proxy.inc << 'EOF'
milter = yes;
timeout = 120s;
bind_socket = "127.0.0.1:11332";
upstream "local" {
  default = yes;
  self_scan = yes;
}
EOF
cat > /etc/rspamd/local.d/worker-controller.inc << 'EOF'
bind_socket = "127.0.0.1:11334";
secure_ip = "127.0.0.1/32";
EOF
cat > /etc/rspamd/local.d/worker-normal.inc << 'EOF'
# The milter proxy self-scans, but keep one normal worker for local rspamc and
# diagnostics. Do not scale this with CPU count on a memory-constrained VPS.
count = 1;
bind_socket = "127.0.0.1:11333";
EOF
cat > /etc/rspamd/local.d/options.inc << 'EOF'
# Compiled Hyperscan maps trade substantial resident memory for throughput.
# PCRE scanning is a better fit for the supported 1 GB, low-volume appliance.
disable_hyperscan = true;
EOF

# Rspamd's standard modules perform SPF, DKIM, DMARC, and ARC checks. Keep
# their Authentication-Results and extended result headers for diagnostics.
cat > /etc/rspamd/local.d/milter_headers.conf << 'EOF'
extended_spam_headers = true;
use = ["x-spamd-bar", "x-spam-status", "authentication-results"];
EOF
cat > /etc/rspamd/local.d/actions.conf << 'EOF'
greylist = 4.0;
add_header = 6.0;
reject = 15.0;
EOF
cat > /etc/rspamd/local.d/greylist.conf << 'EOF'
servers = "127.0.0.1:6379";
timeout = 5m;
expire = 1d;
EOF
cat > /etc/rspamd/local.d/redis.conf << 'EOF'
servers = "127.0.0.1:6379";
EOF
cat > /etc/rspamd/local.d/classifier-bayes.conf << 'EOF'
backend = "redis";
servers = "127.0.0.1:6379";
new_schema = true;
expire = 8640000;
autolearn {
  spam_threshold = 12.0;
  ham_threshold = -2.0;
  check_balance = true;
}
EOF

# Sign locally-originated mail with the existing S5 selector and key. The
# OpenDKIM-compatible tables are regenerated by management/dns_update.py so
# aliases work while unowned From domains are never signed with the S5 key.
cat > /etc/rspamd/local.d/dkim_signing.conf << EOF
enabled = true;
selector = "mail";
signing_table = "/etc/rspamd/s5mail-dkim/SigningTable";
key_table = "/etc/rspamd/s5mail-dkim/KeyTable";
sign_authenticated = true;
sign_local = true;
EOF
cat > /etc/rspamd/local.d/arc.conf << 'EOF'
enabled = true;
# Validate existing ARC chains, but do not add a seal until S5 has a distinct
# appliance ARC identity and published key lifecycle.
sign_inbound = false;
EOF
cat > /etc/rspamd/local.d/neural.conf << 'EOF'
enabled = false;
EOF
chown -R _rspamd:_rspamd /etc/rspamd/local.d
chmod 0640 /etc/rspamd/local.d/*.conf /etc/rspamd/local.d/*.inc
# Keep the key owned by the storage account for backup/DNS administration and
# grant only Rspamd's private group the traversal/read access needed to sign.
chown "${STORAGE_USER}:_rspamd" "$STORAGE_ROOT/mail/dkim"
chmod 0750 "$STORAGE_ROOT/mail/dkim"
chown "${STORAGE_USER}:_rspamd" "$STORAGE_ROOT/mail/dkim/mail.private"
chmod 0640 "$STORAGE_ROOT/mail/dkim/mail.private"

# IMAPSieve replaced the deprecated dovecot-antispam plugin. The wrappers are
# deliberately tiny and receive the message over stdin from Sieve's pipe
# extension, so no credentials or message contents are logged.
install -d -m 0755 /usr/local/libexec/dovecot
install -d -m 0750 -o root -g dovecot /etc/dovecot/sieve/before
# Rspamd's x-spam-status routine emits the SpamAssassin-compatible
# X-Spam-Status: Yes header for add-header actions. Keep delivery filing in
# the native before-scanner directory so it runs before personal Sieve rules.
cp conf/sieve-spam.txt /etc/dovecot/sieve/before/10-rspamd-file-spam.sieve
chown root:dovecot /etc/dovecot/sieve/before/10-rspamd-file-spam.sieve
chmod 0640 /etc/dovecot/sieve/before/10-rspamd-file-spam.sieve
cat > /usr/local/libexec/dovecot/s5mail-rspamd-learn-spam << 'EOF'
#!/bin/sh
exec /usr/bin/rspamc learn_spam
EOF
cat > /usr/local/libexec/dovecot/s5mail-rspamd-learn-ham << 'EOF'
#!/bin/sh
exec /usr/bin/rspamc learn_ham
EOF
chmod 0755 /usr/local/libexec/dovecot/s5mail-rspamd-learn-{spam,ham}
cat > /etc/dovecot/sieve/before/rspamd-learn-spam.sieve << 'EOF'
require ["vnd.dovecot.pipe", "copy", "imapsieve", "environment"];
if environment :is "imap.cause" "COPY" {
  pipe :copy "s5mail-rspamd-learn-spam";
}
EOF
cat > /etc/dovecot/sieve/before/rspamd-learn-ham.sieve << 'EOF'
require ["vnd.dovecot.pipe", "copy", "imapsieve", "environment"];
if environment :is "imap.cause" "COPY" {
  pipe :copy "s5mail-rspamd-learn-ham";
}
EOF
rm -f /etc/dovecot/conf.d/99-local-rspamd-learning.conf
chown root:dovecot /etc/dovecot/sieve/before/rspamd-learn-*.sieve
chmod 0640 /etc/dovecot/sieve/before/rspamd-learn-*.sieve
sievec -c /etc/dovecot/dovecot.conf -P sieve_imapsieve -P sieve_extprograms /etc/dovecot/sieve/before/rspamd-learn-spam.sieve
sievec -c /etc/dovecot/dovecot.conf -P sieve_imapsieve -P sieve_extprograms /etc/dovecot/sieve/before/rspamd-learn-ham.sieve
sievec -c /etc/dovecot/dovecot.conf /etc/dovecot/sieve/before/10-rspamd-file-spam.sieve

hide_output rspamadm configtest

# Remove the retired chain only after its replacement has parsed successfully.
# Leaving any of these enabled after cutover can cause duplicate headers,
# signatures, or greylisting decisions.
for service in spamassassin spampd postgrey opendkim opendmarc redis-server redis; do
	systemctl disable --now "$service" >/dev/null 2>&1 || true
done
legacy_packages=()
for package in spamassassin spampd razor pyzor dovecot-antispam libmail-dkim-perl postgrey opendkim opendkim-tools opendmarc redis-server redis-tools; do
	if dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q '^install ok installed$'; then
		legacy_packages+=("$package")
	fi
done
if [ "${#legacy_packages[@]}" -gt 0 ]; then
	apt_get_quiet purge "${legacy_packages[@]}"
fi
rm -rf /etc/spamassassin /etc/default/spamassassin /etc/default/spampd
rm -rf /etc/postgrey /etc/opendkim /etc/opendmarc
rm -f /etc/cron.daily/mailinabox-postgrey-whitelist /etc/cron.daily/s5mail-postgrey-whitelist

hide_output systemctl enable valkey-server rspamd
restart_service valkey-server
restart_service rspamd
restart_service dovecot
